!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/poem1.txt -o poem1.txt
poem_file=open('poem1.txt','r')   #open file in memory
print(poem_file)
poem_contents=poem_file.read()
print(poem_contents)
poem_file=open('poem1.txt','r')
poem10_char=poem_file.read(10)
print(poem_10char)
poem_file=open('poem1.txt','r')
poem_parts=poem_file.read(10)
print(poem_parts)
poem_file=open('poem1.txt','r')
poem_parts += poem_file.read(5)
print(poem_parts)
poem_file=open('poem1.txt','r')
poem_part = poem_file.read(6).title()
print(poem_part)
poem_file=open('poem1.txt','r')
print(poem_part.isalpha())
poem_file = open('poem1.txt', 'r')
poem_text = poem_file.read()
print(poem_text[8:26])
